export * from 'models/figures/Bishop'
export * from 'models/figures/King'
export * from 'models/figures/Knight'
export * from 'models/figures/Pawn'
export * from 'models/figures/Queen'
export * from 'models/figures/Rook'
